INSERT INTO "walks"
("name", "description", "length_km", "image_url", "difficulty", "region_id")
VALUES ('Mount Victoria Loop',
        'This scenic walk takes you around the top of Mount Victoria, offering stunning views of Wellington and its harbor.',
        3.5,
        'https://images.pexels.com/photos/4350631/pexels-photo-4350631.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'easy',
        (SELECT "id" FROM "regions" WHERE "code" = 'WGN')),
       ('Makara Beach Walkway',
        'This walk takes you along the wild and rugged coastline of Makara Beach, with breathtaking views of the Tasman Sea.',
        8.2,
        'https://images.pexels.com/photos/4350631/pexels-photo-4350631.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'medium',
        (SELECT "id" FROM "regions" WHERE "code" = 'WGN')),
       ('Botanic Garden Walk',
        'Explore the beautiful Botanic Garden of Wellington on this leisurely walk, with a wide variety of plants and flowers to admire.',
        2,
        'https://images.pexels.com/photos/4350631/pexels-photo-4350631.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'easy',
        (SELECT "id" FROM "regions" WHERE "code" = 'WGN')),
       ('Mount Eden Summit Walk',
        'This walk takes you to the summit of Mount Eden, the highest natural point in Auckland, with panoramic views of the city.',
        2,
        'https://images.pexels.com/photos/5342974/pexels-photo-5342974.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'easy',
        (SELECT "id" FROM "regions" WHERE "code" = 'AUK')),
       ('Cornwall Park Walk',
        'Explore the beautiful Cornwall Park on this leisurely walk, with a wide variety of trees, gardens, and animals to admire.',
        3,
        'https://images.pexels.com/photos/5342974/pexels-photo-5342974.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'easy',
        (SELECT "id" FROM "regions" WHERE "code" = 'AUK')),
       ('Takapuna to Milford Coastal Walk',
        'This coastal walk takes you along the beautiful beaches of Takapuna and Milford, with stunning views of Rangitoto Island.',
        5,
        'https://images.pexels.com/photos/5342974/pexels-photo-5342974.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'medium',
        (SELECT "id" FROM "regions" WHERE "code" = 'AUK')),
       ('Centre of New Zealand Walkway',
        'This walk takes you to the geographical centre of New Zealand, with stunning views of Nelson and its surroundings.',
        1.0,
        'https://images.pexels.com/photos/808466/pexels-photo-808466.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'medium',
        (SELECT "id" FROM "regions" WHERE "code" = 'NSN')),
       ('Maitai Valley Walk',
        'Explore the picturesque Maitai Valley on this easy walk, with a tranquil river and native bush to enjoy.',
        5.0,
        'https://images.pexels.com/photos/808466/pexels-photo-808466.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'medium',
        (SELECT "id" FROM "regions" WHERE "code" = 'NSN')),
       ('Boulder Bank Walkway',
        'This coastal walk takes you along the unique Boulder Bank, a long narrow bar of rocks that extends into Tasman Bay.',
        8.0,
        'https://images.pexels.com/photos/808466/pexels-photo-808466.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'hard',
        (SELECT "id" FROM "regions" WHERE "code" = 'NSN')),
       ('Mount Maunganui Summit Walk',
        'This walk takes you to the summit of Mount Maunganui, with stunning views of the ocean and surrounding landscape.',
        3.0,
        'https://images.pexels.com/photos/808466/pexels-photo-808466.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'medium', (SELECT "id" FROM "regions" WHERE "code" = 'BOP')),
       ('The Papamoa Hills Regional Park Walk',
        'Enjoy panoramic views of Tauranga and Mount Maunganui on this walk through the Papamoa Hills, with a mix of bush and open farmland.',
        5.0,
        'https://images.pexels.com/photos/808466/pexels-photo-808466.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'medium',
        (SELECT "id" FROM "regions" WHERE "code" = 'BOP')),
       ('The White Pine Bush Track',
        'Explore the lush and peaceful White Pine Bush on this easy walk, with a variety of native flora and fauna to discover.',
        2.0,
        'https://images.pexels.com/photos/808466/pexels-photo-808466.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'medium',
        (SELECT "id" FROM "regions" WHERE "code" = 'BOP')),
       ('The Bluff Hill Walkway',
        'This walk takes you to the top of Bluff Hill, with panoramic views of Bluff and the surrounding coastline.',
        6.0,
        'https://images.pexels.com/photos/2226900/pexels-photo-2226900.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'medium',
        (SELECT "id" FROM "regions" WHERE "code" = 'STL')),
       ('The Kepler Track',
        'One of New Zealand�s most famous walks, the Kepler Track offers stunning alpine vistas and takes you through a range of landscapes from peaceful beech forests to open tussock lands.',
        32.0,
        'https://images.pexels.com/photos/2226900/pexels-photo-2226900.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'hard',
        (SELECT "id" FROM "regions" WHERE "code" = 'STL')),
       ('The Hump Ridge Track',
        'Experience the stunning scenery of the southern Fiordland and the coast on this challenging multi-day walk, with beautiful forest and alpine views.',
        60.0,
        'https://images.pexels.com/photos/2226900/pexels-photo-2226900.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
        'hard',
        (SELECT "id" FROM "regions" WHERE "code" = 'STL'));
