INSERT INTO "walks"
("name",
 "description",
 "length_km",
 "image_url",
 "region_id",
 "difficulty")
VALUES
    -- Auckland (AUK): multiple walks
    ('Rangitoto Summit Track',
     'A volcanic island walk leading to the summit of Rangitoto with panoramic views across Auckland and the Hauraki Gulf.',
     7.0,
     'https://commons.wikimedia.org/wiki/Special:Redirect/file/Rangitoto_Island_view_of_Auckland_from_Summit_Track.jpg',
     (SELECT "id" FROM "regions" WHERE "code" = 'AUK'),
     'medium'),
    ('Coast to Coast Walkway',
     'An urban walk across Auckland connecting the Waitematā and Manukau harbours through parks and volcanic landscapes.',
     16.0,
     'https://commons.wikimedia.org/wiki/Special:Redirect/file/Auckland%2C_New_Zealand_%2849152589687%29.jpg',
     (SELECT "id" FROM "regions" WHERE "code" = 'AUK'),
     'easy'),
    ('Māngere Mountain Loop',
     'A short walk around one of Auckland''s best-preserved volcanic cones with views over the surrounding suburbs.',
     3.0,
     'https://commons.wikimedia.org/wiki/Special:Redirect/file/Mangere_Mountain.jpg',
     (SELECT "id" FROM "regions" WHERE "code" = 'AUK'),
     'easy'),

    -- Waikato (WKO): multiple walks
    ('Hakarimata Summit Track',
     'A steep forest climb to the Hakarimata summit involving a long staircase and native bush.',
     4.0,
     'https://commons.wikimedia.org/wiki/Special:Redirect/file/Steps_on_Summit_Track%2C_Hakarimata.jpg',
     (SELECT "id" FROM "regions" WHERE "code" = 'WKO'),
     'hard'),
    ('Wairēinga Bridal Veil Falls Track',
     'A short forest walk to viewing platforms overlooking the spectacular Bridal Veil Falls.',
     1.0,
     'https://commons.wikimedia.org/wiki/Special:Redirect/file/Bridal_Veil_Falls%2C_Waikato%2C_New_Zealand.jpg',
     (SELECT "id" FROM "regions" WHERE "code" = 'WKO'),
     'easy'),

    -- Wellington (WGN): exactly one walk
    ('Mount Victoria Lookout Walk',
     'A walk through Wellington''s town belt to Mount Victoria Lookout with views across the city and harbour.',
     4.6,
     'https://commons.wikimedia.org/wiki/Special:Redirect/file/Mt_Victoria_Lookout.jpg',
     (SELECT "id" FROM "regions" WHERE "code" = 'WGN'),
     'medium'),

    -- Canterbury (CAN): multiple walks
    ('Hooker Valley Track',
     'A popular alpine walk through the Hooker Valley with suspension bridges and views towards Aoraki Mount Cook.',
     10.0,
     'https://commons.wikimedia.org/wiki/Special:Redirect/file/NZ_Hooker_Valley_track.jpg',
     (SELECT "id" FROM "regions" WHERE "code" = 'CAN'),
     'medium'),
    ('Sealy Tarns Track',
     'A steep alpine climb above the Hooker Valley with extensive views of Aoraki Mount Cook and surrounding glaciers.',
     5.8,
     'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sealy_Tarns_Track%2C_Aoraki_-_Mount_Cook_National_Park%2C_New_Zealand.jpg',
     (SELECT "id" FROM "regions" WHERE "code" = 'CAN'),
     'hard'),
    ('Mueller Hut Route',
     'A demanding alpine route climbing above Sealy Tarns to Mueller Hut in Aoraki Mount Cook National Park.',
     10.4,
     'https://commons.wikimedia.org/wiki/Special:Redirect/file/Mueller_Hut_Route%2C_Mount_Cook_National_Park%2C_New_Zealand_%28Unsplash%29.jpg',
     (SELECT "id" FROM "regions" WHERE "code" = 'CAN'),
     'expert'),

    -- Otago (OTA): multiple walks
    ('Roys Peak Track',
     'A long and steep climb above Lake Wānaka offering extensive views over the lake and surrounding mountains.',
     16.0,
     'https://commons.wikimedia.org/wiki/Special:Redirect/file/Roys_Peak.jpg',
     (SELECT "id" FROM "regions" WHERE "code" = 'OTA'),
     'hard'),
    ('Ben Lomond Track',
     'A challenging mountain walk from Queenstown climbing towards Ben Lomond summit with views over Lake Wakatipu.',
     14.0,
     'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ben-Lomond-summit.jpg',
     (SELECT "id" FROM "regions" WHERE "code" = 'OTA'),
     'expert');

-- GBN intentionally has no walks.